numbers = list(range(10))
print(numbers)
numbers = list(range(345))
print(numbers)
alphabet = list(range(45))
print(alphabet)
Alpha =list (range(10))
print(Alpha)
swati = list(range(46))
print (swati)
numbers =list (range(8))
print (numbers )